import React, { useState, useCallback } from 'react';
import { StyleSheet, View, Text, FlatList, TouchableOpacity, ActivityIndicator, Alert, ViewStyle, TextStyle, Dimensions } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { useAuth } from '@/context/AuthContext';
import { getAllHistory, getAdminUsers, AdminHistoryItem, AdminUser } from '@/services/ml/api';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { BrandColors } from '@/constants/theme';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const { width } = Dimensions.get('window');

export default function AdminTrackingScreen() {
  const { token } = useAuth();
  const [history, setHistory] = useState<AdminHistoryItem[]>([]);
  const [users, setUsers] = useState<AdminUser[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedUserId, setSelectedUserId] = useState<number | undefined>(undefined);

  const fetchData = async () => {
    if (!token) return;
    try {
      setLoading(true);
      const [hist, usrs] = await Promise.all([
        getAllHistory(token, 50, selectedUserId),
        getAdminUsers(token)
      ]);
      setHistory(hist);
      setUsers(usrs);
    } catch (error: any) {
      console.error("Failed to load tracking data", error);
    } finally {
      setLoading(false);
    }
  };

  useFocusEffect(useCallback(() => { fetchData(); }, [token, selectedUserId]));

  const selectedUser = users.find(u => u.id === selectedUserId);

  const exportToPDF = async (item: AdminHistoryItem) => {
    const isFraud = item.prediction === 1;
    const html = `
      <html>
        <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #091E42;">
          <div style="border-bottom: 2px solid ${BrandColors.primary}; padding-bottom: 20px; margin-bottom: 30px;">
            <h1 style="color: ${BrandColors.primary}; margin: 0; font-size: 28px;">FraudGuard Intelligence</h1>
            <p style="color: #5E6C84; margin-top: 5px; font-weight: 500;">Admin Tracking Report</p>
          </div>
          
          <div style="background-color: ${isFraud ? '#FFF5F5' : '#F0FFF4'}; padding: 25px; border-radius: 12px; border: 1px solid ${isFraud ? BrandColors.danger : BrandColors.success}; margin-bottom: 30px;">
            <h2 style="font-size: 22px; margin: 0; color: ${isFraud ? BrandColors.danger : BrandColors.success};">
              SCAN STATUS: ${isFraud ? 'THREAT DETECTED' : 'SECURE'}
            </h2>
            <p style="margin: 10px 0 0 0; font-weight: bold; font-size: 16px;">
              Probability Score: ${(item.probability * 100).toFixed(2)}%
            </p>
          </div>
          
          <table style="width: 100%; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #EDF2F7;">
              <td style="padding: 15px; font-weight: bold; color: #64748B;">User</td>
              <td style="padding: 15px; text-align: right;">${item.username}</td>
            </tr>
            <tr style="border-bottom: 1px solid #EDF2F7;">
              <td style="padding: 15px; font-weight: bold; color: #64748B;">Transaction ID</td>
              <td style="padding: 15px; text-align: right;">#FG-${item.id}</td>
            </tr>
            <tr style="border-bottom: 1px solid #EDF2F7;">
              <td style="padding: 15px; font-weight: bold; color: #64748B;">Date & Time</td>
              <td style="padding: 15px; text-align: right;">${new Date(item.timestamp).toLocaleString('en-US', { timeZone: 'Asia/Karachi' })} PKT</td>
            </tr>
            <tr style="border-bottom: 1px solid #EDF2F7;">
              <td style="padding: 15px; font-weight: bold; color: #64748B;">Transfer Type</td>
              <td style="padding: 15px; text-align: right; text-transform: uppercase;">${item.type}</td>
            </tr>
            <tr style="border-bottom: 1px solid #EDF2F7;">
              <td style="padding: 15px; font-weight: bold; color: #64748B;">Transaction Amount</td>
              <td style="padding: 15px; text-align: right; font-weight: bold; font-size: 18px;">$${item.amount.toLocaleString(undefined, {minimumFractionDigits: 2})}</td>
            </tr>
          </table>

          <div style="margin-top: 60px; font-size: 12px; color: #A5ADBA; text-align: center; border-top: 1px dashed #DFE1E6; paddingTop: 20px;">
            <p>This report was generated by the FraudGuard AI real-time detection module.</p>
            <p>Internal Reference: ${item.id} | Machine Generated</p>
          </div>
        </body>
      </html>
    `;

    try {
      const { uri } = await Print.printToFileAsync({ html });
      if (await Sharing.isAvailableAsync()) {
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
      } else {
        Alert.alert('Success', 'Report generated successfully.');
      }
    } catch (error) {
      Alert.alert('Export Failure', 'Could not generate the PDF intelligence report.');
    }
  };

  return (
    <View style={viewStyles.container}>
      <View style={viewStyles.topCurvedBackground} />
      <View style={viewStyles.header}>
        <Text style={textStyles.title}>Transaction Tracking</Text>
        <Text style={textStyles.subtitle}>All-user activity feed</Text>
        <FlatList
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={viewStyles.filterContent}
          data={[{ id: undefined, username: 'All' } as any, ...users]}
          keyExtractor={(item) => String(item.id || 'all')}
          renderItem={({ item }) => (
            <TouchableOpacity
              style={[viewStyles.filterChip, selectedUserId === item.id && viewStyles.activeFilterChip]}
              onPress={() => setSelectedUserId(item.id)}
            >
              <Text style={[textStyles.filterText, selectedUserId === item.id && textStyles.activeFilterText]}>
                {item.username}
              </Text>
            </TouchableOpacity>
          )}
        />
      </View>

      {loading ? (
        <View style={viewStyles.centerBox}>
          <ActivityIndicator size="large" color={BrandColors.primary} />
        </View>
      ) : (
        <FlatList
          data={history}
          keyExtractor={(item) => item.id.toString()}
          contentContainerStyle={viewStyles.listContent}
          showsVerticalScrollIndicator={false}
          renderItem={({ item }) => {
            const isFraud = item.prediction === 1;
            return (
              <View style={[viewStyles.txCard, { borderLeftColor: isFraud ? BrandColors.danger : BrandColors.success }]}>
                <View style={viewStyles.cardRow}>
                  <View style={viewStyles.txLeft}>
                    <Text style={textStyles.txUser}>{item.username}</Text>
                    <Text style={textStyles.txType}>{item.type.replace('_', ' ')}</Text>
                  </View>
                  <View style={viewStyles.txRight}>
                    <Text style={[textStyles.txAmount, { color: isFraud ? BrandColors.danger : BrandColors.textMain }]}>
                      ${item.amount >= 1000 ? (item.amount / 1000).toFixed(1) + 'k' : item.amount.toLocaleString()}
                    </Text>
                    <View style={[viewStyles.statusDot, { backgroundColor: isFraud ? BrandColors.danger : BrandColors.success }]} />
                  </View>
                </View>
                <View style={viewStyles.cardRow}>
                  <Text style={textStyles.txDate}>
                    {new Date(item.timestamp).toLocaleString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })}
                  </Text>
                  <TouchableOpacity
                    style={viewStyles.exportBtn}
                    onPress={() => exportToPDF(item)}
                    activeOpacity={0.7}
                  >
                    <IconSymbol name="plus.circle.fill" size={14} color={BrandColors.primary} />
                    <Text style={textStyles.exportText}>Report</Text>
                  </TouchableOpacity>
                </View>
              </View>
            );
          }}
          ListEmptyComponent={
            <View style={viewStyles.centerBox}>
              <IconSymbol name="doc.text.fill" size={60} color={BrandColors.border} />
              <Text style={textStyles.emptyText}>No transactions found</Text>
            </View>
          }
        />
      )}
    </View>
  );
}

const viewStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BrandColors.background } as ViewStyle,
  topCurvedBackground: {
    position: 'absolute', top: 0, left: 0, right: 0, height: 280,
    backgroundColor: '#EBF4FF', borderBottomLeftRadius: 80, opacity: 0.7,
  } as ViewStyle,
  header: { padding: 24, paddingTop: 64, paddingBottom: 8 } as ViewStyle,
  centerBox: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingBottom: 100 } as ViewStyle,
  filterContent: { paddingVertical: 16, gap: 10 } as ViewStyle,
  filterChip: {
    paddingHorizontal: 18, paddingVertical: 10, borderRadius: 20,
    backgroundColor: BrandColors.white, borderWidth: 1.5, borderColor: BrandColors.border,
    marginRight: 10,
  } as ViewStyle,
  activeFilterChip: {
    backgroundColor: BrandColors.primary, borderColor: BrandColors.primary,
  } as ViewStyle,
  listContent: { padding: 24, paddingTop: 0, paddingBottom: 120 } as ViewStyle,
  txCard: {
    backgroundColor: BrandColors.white, borderRadius: 20, padding: 18, marginBottom: 12,
    borderLeftWidth: 4,
    shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.04, shadowRadius: 10, elevation: 2,
  } as ViewStyle,
  cardRow: {
    flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
  } as ViewStyle,
  txLeft: {} as ViewStyle,
  txRight: { flexDirection: 'row', alignItems: 'center', gap: 8 } as ViewStyle,
  statusDot: { width: 8, height: 8, borderRadius: 4 } as ViewStyle,
  exportBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    backgroundColor: '#EBF4FF', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 14, marginTop: 8,
  } as ViewStyle,
});

const textStyles = StyleSheet.create({
  title: { fontSize: 28, fontWeight: '900', letterSpacing: -1, color: BrandColors.textMain } as TextStyle,
  subtitle: { fontSize: 14, fontWeight: '600', color: BrandColors.textSub, marginTop: 4 } as TextStyle,
  filterText: { fontSize: 13, fontWeight: '800', color: BrandColors.textSub } as TextStyle,
  activeFilterText: { color: '#FFFFFF' } as TextStyle,
  txUser: { fontSize: 16, fontWeight: '900', color: BrandColors.textMain } as TextStyle,
  txType: { fontSize: 12, fontWeight: '700', color: BrandColors.textSub, marginTop: 2, textTransform: 'uppercase', letterSpacing: 0.3 } as TextStyle,
  txAmount: { fontSize: 18, fontWeight: '900', letterSpacing: -0.5 } as TextStyle,
  txDate: { fontSize: 12, fontWeight: '600', color: BrandColors.textSub, marginTop: 8 } as TextStyle,
  txProb: { fontSize: 12, fontWeight: '900', marginTop: 8 } as TextStyle,
  emptyText: { fontSize: 16, fontWeight: '800', color: BrandColors.textSub, marginTop: 16 } as TextStyle,
  exportText: {
    fontSize: 13, fontWeight: '900', color: BrandColors.primary,
  } as TextStyle,
});
