import React, { useEffect, useState, useCallback } from 'react';
import { StyleSheet, View, Text, FlatList, TouchableOpacity, ActivityIndicator, Alert, ViewStyle, TextStyle, Dimensions } from 'react-native';
import { useFocusEffect } from 'expo-router';
import { useAuth } from '@/context/AuthContext';
import { getHistory, HistoryItem } from '@/services/ml/api';
import { IconSymbol } from '@/components/ui/icon-symbol';
import { BrandColors } from '@/constants/theme';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

const { width } = Dimensions.get('window');

export default function HistoryScreen() {
    const { token } = useAuth();
    const [history, setHistory] = useState<HistoryItem[]>([]);
    const [loading, setLoading] = useState(true);

    const fetchHistory = async () => {
        if (!token) return;
        try {
            setLoading(true);
            const data = await getHistory(token);
            setHistory(data);
        } catch (error: any) {
            Alert.alert("History Error", error.message || "Failed to load scan records.");
        } finally {
            setLoading(false);
        }
    };

    useFocusEffect(
        useCallback(() => {
            fetchHistory();
        }, [token])
    );

    const exportToPDF = async (item: HistoryItem) => {
        const html = `
            <html>
                <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #091E42;">
                    <div style="border-bottom: 2px solid ${BrandColors.primary}; padding-bottom: 20px; margin-bottom: 30px;">
                        <h1 style="color: ${BrandColors.primary}; margin: 0; font-size: 28px;">FraudGuard Intelligence</h1>
                        <p style="color: #5E6C84; margin-top: 5px; font-weight: 500;">Automated Transaction Security Report</p>
                    </div>
                    
                    <div style="background-color: ${item.prediction === 1 ? '#FFF5F5' : '#F0FFF4'}; padding: 25px; border-radius: 12px; border: 1px solid ${item.prediction === 1 ? BrandColors.danger : BrandColors.success}; margin-bottom: 30px;">
                        <h2 style="font-size: 22px; margin: 0; color: ${item.prediction === 1 ? BrandColors.danger : BrandColors.success};">
                            SCAN STATUS: ${item.prediction === 1 ? 'THREAT DETECTED' : 'SECURE'}
                        </h2>
                        <p style="margin: 10px 0 0 0; font-weight: bold; font-size: 16px;">
                            Probability Score: ${(item.probability * 100).toFixed(2)}%
                        </p>
                    </div>
                    
                    <table style="width: 100%; border-collapse: collapse;">
                        <tr style="border-bottom: 1px solid #EDF2F7;">
                            <td style="padding: 15px; font-weight: bold; color: #64748B;">Transaction ID</td>
                            <td style="padding: 15px; text-align: right;">#FG-${item.id}-${new Date(item.timestamp).getTime()}</td>
                        </tr>
                        <tr style="border-bottom: 1px solid #EDF2F7;">
                            <td style="padding: 15px; font-weight: bold; color: #64748B;">Date & Time</td>
                            <td style="padding: 15px; text-align: right;">${new Date(item.timestamp).toLocaleString('en-US', { timeZone: 'Asia/Karachi' })} PKT</td>
                        </tr>
                        <tr style="border-bottom: 1px solid #EDF2F7;">
                            <td style="padding: 15px; font-weight: bold; color: #64748B;">Transfer Type</td>
                            <td style="padding: 15px; text-align: right; text-transform: uppercase;">${item.type}</td>
                        </tr>
                        <tr style="border-bottom: 1px solid #EDF2F7;">
                            <td style="padding: 15px; font-weight: bold; color: #64748B;">Transaction Amount</td>
                            <td style="padding: 15px; text-align: right; font-weight: bold; font-size: 18px;">$${item.amount.toLocaleString(undefined, {minimumFractionDigits: 2})}</td>
                        </tr>
                    </table>

                    <div style="margin-top: 60px; font-size: 12px; color: #A5ADBA; text-align: center; border-top: 1px dashed #DFE1E6; paddingTop: 20px;">
                        <p>This report was generated by the FraudGuard AI real-time detection module.</p>
                        <p>Internal Reference: ${item.id} | Machine Generated</p>
                    </div>
                </body>
            </html>
        `;

        try {
            const { uri } = await Print.printToFileAsync({ html });
            if (await Sharing.isAvailableAsync()) {
                await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
            } else {
                Alert.alert('Success', 'Report generated successfully.');
            }
        } catch (error) {
            Alert.alert('Export Failure', 'Could not generate the PDF intelligence report.');
        }
    };

    const renderItem = ({ item }: { item: HistoryItem }) => {
        const isFraud = item.prediction === 1;
        const statusColor = isFraud ? BrandColors.danger : BrandColors.success;
        const statusBg = isFraud ? '#FFF5F5' : '#F0FFF4';
        const iconName = isFraud ? "exclamationmark.shield.fill" : "checkmark.shield.fill";

        return (
            <View style={viewStyles.historyCard}>
                <View style={viewStyles.cardHeader}>
                    <View style={viewStyles.headerLeft}>
                        <View style={[viewStyles.iconBg, { backgroundColor: isFraud ? BrandColors.lightRed : BrandColors.lightGreen }]}>
                            <IconSymbol name={iconName} size={20} color={statusColor} />
                        </View>
                        <View>
                            <Text style={textStyles.txType}>{item.type.replace('_', ' ')}</Text>
                            <Text style={textStyles.txDate}>
                                {new Date(item.timestamp).toLocaleString('en-US', { timeZone: 'Asia/Karachi', month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })} PKT
                            </Text>
                        </View>
                    </View>
                    <Text style={textStyles.txAmount}>
                        ${item.amount >= 1000 ? (item.amount/1000).toFixed(1) + 'k' : item.amount.toLocaleString()}
                    </Text>
                </View>

                <View style={viewStyles.cardDivider} />

                <View style={viewStyles.cardFooter}>
                    <View style={[viewStyles.statusBadge, { backgroundColor: statusBg, borderColor: statusColor + '40' }]}>
                        <View style={[viewStyles.statusDot, { backgroundColor: statusColor }]} />
                        <Text style={[textStyles.statusText, { color: statusColor }]}>
                            {isFraud ? 'THREAT' : 'SECURE'} Index: {(item.probability * 100).toFixed(1)}%
                        </Text>
                    </View>
                    
                    <TouchableOpacity 
                        style={viewStyles.exportBtn} 
                        onPress={() => exportToPDF(item)}
                        activeOpacity={0.7}
                    >
                        <IconSymbol name="plus.circle.fill" size={14} color={BrandColors.primary} />
                        <Text style={textStyles.exportText}>Report</Text>
                    </TouchableOpacity>
                </View>
            </View>
        );
    };

    return (
        <View style={viewStyles.container}>
            <View style={viewStyles.topCurvedBackground} />
            
            <View style={viewStyles.header}>
                <Text style={textStyles.title}>Scan History</Text>
                <Text style={textStyles.subtitle}>Audit trail of recent transaction intelligence.</Text>
            </View>

            {loading ? (
                <View style={viewStyles.centerBox}>
                    <ActivityIndicator size="large" color={BrandColors.primary} />
                </View>
            ) : history.length === 0 ? (
                <View style={viewStyles.centerBox}>
                    <View style={viewStyles.emptyIconBox}>
                        <IconSymbol name="shield.fill" size={60} color={BrandColors.border} />
                    </View>
                    <Text style={textStyles.emptyText}>No operations logged yet.</Text>
                </View>
            ) : (
                <FlatList
                    data={history}
                    keyExtractor={(item) => item.id.toString()}
                    renderItem={renderItem}
                    contentContainerStyle={viewStyles.listContent}
                    showsVerticalScrollIndicator={false}
                />
            )}
        </View>
    );
}

const viewStyles = StyleSheet.create({
    container: { 
        flex: 1, 
        backgroundColor: BrandColors.background 
    } as ViewStyle,
    topCurvedBackground: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: 280,
        backgroundColor: '#EBF4FF',
        borderBottomRightRadius: 80,
        opacity: 0.7,
    } as ViewStyle,
    header: { 
        padding: 24, 
        paddingTop: 64, 
        paddingBottom: 24 
    } as ViewStyle,
    centerBox: { 
        flex: 1, 
        justifyContent: 'center', 
        alignItems: 'center', 
        paddingBottom: 100 
    } as ViewStyle,
    emptyIconBox: {
        width: 100,
        height: 100,
        borderRadius: 50,
        backgroundColor: '#F4F5F7',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20
    } as ViewStyle,
    listContent: { 
        padding: 24, 
        paddingTop: 0, 
        paddingBottom: 120 
    } as ViewStyle,
    historyCard: { 
        backgroundColor: BrandColors.white,
        borderRadius: 28, 
        padding: 20, 
        marginBottom: 16, 
        borderWidth: 1, 
        borderColor: BrandColors.border,
        shadowColor: '#000', 
        shadowOffset: { width: 0, height: 8 }, 
        shadowOpacity: 0.04, 
        shadowRadius: 15,
        elevation: 3 
    } as ViewStyle,
    cardHeader: { 
        flexDirection: 'row', 
        justifyContent: 'space-between', 
        alignItems: 'center' 
    } as ViewStyle,
    headerLeft: { 
        flexDirection: 'row', 
        alignItems: 'center', 
        gap: 12 
    } as ViewStyle,
    iconBg: { 
        width: 48, 
        height: 48, 
        borderRadius: 24, 
        justifyContent: 'center', 
        alignItems: 'center' 
    } as ViewStyle,
    cardDivider: { 
        height: 1, 
        backgroundColor: '#F8FAFC', 
        marginVertical: 16 
    } as ViewStyle,
    cardFooter: { 
        flexDirection: 'row', 
        justifyContent: 'space-between', 
        alignItems: 'center' 
    } as ViewStyle,
    statusBadge: { 
        flexDirection: 'row', 
        alignItems: 'center', 
        paddingHorizontal: 16, 
        paddingVertical: 8, 
        borderRadius: 20,
        borderWidth: 1
    } as ViewStyle,
    statusDot: { 
        width: 6, 
        height: 6, 
        borderRadius: 3, 
        marginRight: 8 
    } as ViewStyle,
    exportBtn: { 
        flexDirection: 'row', 
        alignItems: 'center', 
        gap: 8, 
        backgroundColor: '#EBF4FF', 
        paddingHorizontal: 16, 
        paddingVertical: 10, 
        borderRadius: 14 
    } as ViewStyle,
});

const textStyles = StyleSheet.create({
    title: { 
        fontSize: 34, 
        fontWeight: '900', 
        letterSpacing: -1,
        color: BrandColors.textMain 
    } as TextStyle,
    subtitle: { 
        fontSize: 15, 
        fontWeight: '600',
        color: BrandColors.textSub,
        marginTop: 4
    } as TextStyle,
    emptyText: { 
        fontSize: 16, 
        fontWeight: '800',
        color: BrandColors.textSub 
    } as TextStyle,
    txType: { 
        fontSize: 16, 
        fontWeight: '900',
        color: BrandColors.textMain,
        letterSpacing: -0.3
    } as TextStyle,
    txDate: { 
        fontSize: 12, 
        marginTop: 4, 
        fontWeight: '600',
        color: BrandColors.textSub 
    } as TextStyle,
    txAmount: { 
        fontSize: 20, 
        fontWeight: '900',
        color: BrandColors.textMain,
        letterSpacing: -0.5
    } as TextStyle,
    statusText: { 
        fontSize: 12, 
        fontWeight: '900', 
        textTransform: 'uppercase',
        letterSpacing: 0.5
    } as TextStyle,
    exportText: { 
        fontSize: 13, 
        fontWeight: '900',
        color: BrandColors.primary
    } as TextStyle,
});
